### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by Olindn** [namelivia/fitbit-http-php#103]
Hi!

Any reason why there is no PHP 8.0 support?

If you're open to it I'd like to make a PR.

**Comment by namelivia** [comment]
No reason at all but lack of time, if you would like to contribute I would be very very thankful :pray:

**Comment by Olindn** [comment]
Awesome, see https://github.com/namelivia/fitbit-http-php/pull/104

**Comment by namelivia** [comment]
Thanks!
I've tagged `0.0.15` with the PHP 8 supported version.
